import * as React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SvgIcon } from '@mui/material'
import MySvgIcon from '/public/assets/my-logo.svg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          {/* Breaks with error: Element Type is invalid: expected a string */}
          {/* <SvgIcon component={MySvgIcon} /> */}
          <SvgIcon>
            <MySvgIcon />
          </SvgIcon>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}